"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
const { ccclass } = cc._decorator;
let PanelConst = class PanelConst {
    static AscensionEffect = "AscensionEffect";
    static ShowNewEquip = "ShowNewEquip";
    static MESSAGE_PANEL = "MessagePanel";
    static RoamPanel = "RoamPanel";
    static ColorSignHighlight = "ColorSignHighlight";
    static UnlockNewArtifacts = "UnlockNewArtifacts";
    static MessageDialog = "MessageDialog";
    static ChallengeLosePanel = "ChallengeLosePanel";
    static UnlockPet = "UnlockPet";
    static ShareRecorder = "ShareRecorder";
    static ReincarnationPanel = "ReincarnationPanel";
    static RewardPanel = "RewardPanel";
    static RoamNewLine = "RoamNewLine";
    static DETAILS_PANEL = "DetailsPanel";
    static FreeBox = "FreeBox";
    static MapsPanel = "MapsPanel";
    static CartoonPanel = "CartoonPanel";
    static ReincarnationSprite = "ReincarnationSprite";
    static FreeGold = "FreeGold";
    static DisasterPanel = "DisasterPanel";
    static DISCIPLE_PANEL = "DisciplePanel";
    static BuildUpPanel = "BuildUpPanel";
    static StartGame = "StartGame";
    static ShopPanel = "ShopPanel";
    static EquipMessage = "EquipMessage";
    static UnlockDisciple = "UnlockDisciple";
    static PET_PANEL = "PetPanel";
    static NEWRESULT_PANEL = "NewResultPanel";
    static TalkPanel = "TalkPanel";
    static OffLinePanel = "OffLinePanel";
    static TrialsPanel = "TrialsPanel";
    static REALM_PANEL = "RealmPanel";
    static ForewordPanel = "ForewordPanel";
    static SaveToDesktop = "SaveToDesktop";
    static TeachPanel = "TeachPanel";
    static OnlinePanel = "OnlinePanel";
    static GiveUpPanel = "GiveUpPanel";
    static OptionsPanel = "OptionsPanel";
    static TASK_PANEL = "TaskPanel";
    static INTENSIFY_PANEL = "IntensifyPanel";
    static ALCHEMY_PANEL = "AlchemyPanel";
    static UnlockSys = "UnlockSys";
    static ARTIFACTS = "ArtifactsPanel";
    static FreeCoin = "FreeCoin";
    static SignPanel = "SignPanel";
    static RefreshBox = "RefreshBox";
    static RoamChallenge = "RoamChallenge";
    static DevilPanel = "DevilPanel";
    static EquipPanel = "EquipPanel";
    static FreeJewel = "FreeJewel";
    static RealmAddPanel = "RealmAddPanel";
    static PACK_PANEL = "PackPanel";
    static RoamReward = "RoamReward";
    static Sect = "Sect";
    static IllusionPanel = "IllusionPanel";
    static DoublePanel = "DoublePanel";
};
PanelConst = __decorate([
    ccclass
], PanelConst);
exports.default = PanelConst;
