export default class GameSystem extends cc.Component {
    static drugnum: number[];
    static team: any[];
    static shopboxtime: number[];
    static petexp2: number[];
    static roamboxisget: number[];
    static petlevel2: number[];
    static award: number[];
    static shopboxnum: number[];
    static unlockartifacts: number[];
    static goods: number[];
    static guide: number[];
    static landmark: number[];
    static discipleLv: any[];
    static drugboxnum: number[];
    static drugover: number[];
    static intensifyLv: number[];
    static everyday: any[];
    static roambox: number[];
    static skilllevel: number[];
    static reftime: number[];
    static buildlv: number[];
    static artifactslist: number[];
    static onlineisget: number[];
    static drugtime: number[];
    static pack: any[];
    static SkillLJ: any;
    static rewardItem: any;
    static raiseditem: any;
    static CombatBoost: any;
    static isjumpguide: boolean;
    static fightTxt: any;
    static maxlevel: number;
    static FlameEffect: any;
    static Eddy: any;
    static isaddColorSign: boolean;
    static channel: string;
    static adaward_nexttime: number;
    static day: number;
    static resetTime: number;
    static signisget: boolean;
    static disater: number;
    static tier: number;
    static devil: number;
    static speed: number;
    static yehuo: any;
    static artifacts: any;
    static wzlxHit: any;
    static userid: string;
    static saveTime: number;
    static BaneMatrix: any;
    static equipitem: any;
    static PersistentHeal: any;
    static buttet: any;
    static StarEffect: any;
    static petIndex: number;
    static meteor: any;
    static interTime: number;
    static reincarncount: number;
    static addTime: number;
    static disciple: any;
    static spectrum: any;
    static serverTime: number;
    static HealingMatrix: any;
    static GuideMonster: any;
    static Speed: boolean;
    static maxtier: number;
    static music: boolean;
    static resume: number;
    static SkillHC: any;
    static dicetime: number;
    static coin: number;
    static maxartifacts: number;
    static isShowVideoAd: boolean;
    static _tipTxt: any;
    static everydaycount: number;
    static danMadicine: any;
    static level: number;
    static dicenum: number;
    static gold: number;
    static isAddToDesktop: boolean;
    static drugcount: number;
    static isShowInterAd: boolean;
    static SkillSp: any;
    static online: number;
    static sound: boolean;
    static MoonEffect: any;
    static goodsitem: any;
    static isShowBannerAd: boolean;
    static ThunderEffect: any;
    static WindEffect: any;
    static resetcount: number;
    static customs: number;
    static automatic: boolean;
    static Fireball: any;
    static doMove: boolean;
    static CoinIcon: any;
    static shopref: number;
    static sex: number;
    static todayTime: number;
    static openid: string;
    static monster: any;
    static packitem: any;
    static islogin: boolean;
    static SectText: any;
    static Flamepalm: any;
    static makecount: number;
    static shopcount: number;
    static reincarn: number;
    static intensivecount: number;
    static Knife: any;
    static realmexp: number;
    static doBreak: boolean;
    static star: any;
    static maxcustoms: number;
    static nowartifacts: number;
    static isdorecorder: boolean;
    static jewel: number;
    static roamexp: number;
    static OutputCoin: any;
    static roamboxitem: any;
    static isFirstLoad: boolean;
    static pos: number;
    static HeatHalo: any;
    static buycount: number;
    static mopup: number;
    static tick: boolean;
    static roamcount: number;
    static splashAdCount: number;
    static getTier(): number;
    static setResetCount(v: number): void;
    static setGoods(v: number[]): void;
    static setDrugBoxNum(v: number[]): void;
    static initEveryDay(): any[];
    static setShopRefCount(reset?: boolean): void;
    static getCoin(): number;
    static setDisciple(v: any[]): void;
    static setMaxCustoms(v: number): void;
    static addJewel(v: number): void;
    static setAutomatic(): void;
    static setShopBoxNum(v: number[]): void;
    static getMaxTier(): number;
    static setOnlineIsGet(idx: number): void;
    static getEveryDay(): any[];
    static getMaxArtifacts(): number;
    static getMakeCount(): number;
    static setPack(v: any[]): void;
    static getRealmExp(): number;
    static getaddColorSign(): boolean;
    static getGoods(): number[];
    static addCoin(v: number): void;
    static setisAddToDesktop(): void;
    static getPetLevel(): number[];
    static getPos(): number;
    static getSound(): boolean;
    static initLandMark(): number[];
    static addAdCount(): void;
    static setaddColorSign(): void;
    static getRoamBox(): number[];
    static setDrugCount(v: number): void;
    static setPetIndex(v: number): void;
    static setEveryDayCount(): void;
    static getGuide(): number[];
    static getRefTime(): number[];
    static setPetLevel(idx: number, v: number): void;
    static setUnlockArtifacts(): void;
    static setRoamBoxIsGet(v: number[]): void;
    static getBuyCount(): number;
    static setIsFristLoad(): void;
    static setMakeCount(): void;
    static getArtifactslist(): number[];
    static getAdNextTime(): number;
    static getRoamExp(): number;
    static setMopUp(v: number): void;
    static getLandmark(): number[];
    static setArtifactslist(v: number[]): void;
    static getMopUp(): number;
    static getBuildLv(): number[];
    static setRoamBox(v: number[]): void;
    static getDiceNum(): number;
    static getUnlockArtifacts(): number[];
    static setMaxTier(v: number): void;
    static setPetExp(idx: number, v: number): void;
    static setTeam(v: any[]): void;
    static getPetIndex(): number;
    static getAward(): number[];
    static getGold(): number;
    static setGuide(v: number[]): void;
    static setShopBoxTime(v: number[]): void;
    static setSignIsGet(): void;
    static getSignIsGet(): boolean;
    static initGoods(): number[];
    static LoadGameDate(): void;
    static getMaxCustoms(): number;
    static getSpeed(): boolean;
    static setDrugNum(v: number[]): void;
    static getNowArtifacts(): number;
    static getDiceTime(): number;
    static setRoamCount(): void;
    static getIsFirst(): boolean;
    static setRealmExp(v: number): void;
    static getDrugTime(): number[];
    static getPlayerId(): string;
    static getRoamCount(): number;
    static setDiceTime(v: number): void;
    static setAdNextTime(v: number): void;
    static getDay(): number;
    static getOnlineIsGet(): number[];
    static getIntensiveCount(): number;
    static setReincarn(v: number): void;
    static getShopBoxTime(): number[];
    static setRoamExp(v: number): void;
    static setDiceNum(v: number): void;
    static getPack(): any[];
    static getOffTime(): number;
    static getShopBoxNum(): number[];
    static setIntensiveCount(): void;
    static setSex(v: number): void;
    static getOnline(): number;
    static setOnline(v: number): void;
    static getDrugOver(): number[];
    static setEveryDay(v: any[]): void;
    static getInviteNum(): number;
    static getEveryDayCount(): number;
    static setRefTime(v: number[]): void;
    static setMusic(v: boolean): void;
    static getInviteFinish(): number;
    static setIntensify(idx: number): void;
    static initAward(): number[];
    static setBuyCount(reset?: boolean): void;
    static getGoodsItem(): any;
    static getAdCount(): number;
    static setSound(v: boolean): void;
    static setGoodsItem(v: any): void;
    static setAward(v: number[]): void;
    static getisAddToDesktop(): boolean;
    static initArtifacts(): number[];
    static setLevel(v?: number): void;
    static initSkillLevel(): void;
    static setReincarnCount(v: number): void;
    static getSex(): number;
    static getRoamBoxIsGet(): number[];
    static getPetExp(): number[];
    static getMaxLevel(): number;
    static setMaxLevel(v: number): void;
    static initTeam(): any[];
    static setResume(): void;
    static getIntensify(): number[];
    static SaveGameDate(): void;
    static initDisciple(): any[];
    static setOffTime(): void;
    static setMaxArtifacts(v: number): void;
    static setLandmark(idx: number): void;
    static setShopCount(): void;
    static getShopRefCount(): number;
    static setNowArtifacts(v: number): void;
    static getDrugNum(): number[];
    static setTier(v: number): void;
    static setSkillLevel(idx: number): void;
    static getReincarn(): number;
    static setDrugOver(v: number[]): void;
    static setDrugTime(v: number[]): void;
    static getLevel(): number;
    static setBuildLv(v: number[]): void;
    static getResetCount(): number;
    static getTeam(): any[];
    static getReincarnCount(): number;
    static getDrugBoxNum(): number[];
    static _clearGameData(): void;
    static setCustoms(v: number): void;
    static getResume(): number;
    static getSkillLevel(): number[];
    static getDisciple(): any[];
    static getDevil(): number;
    static getShopCount(): number;
    static getMusic(): boolean;
    static Plate(): void;
    static addGold(v: number): void;
    static setSpeed(v: boolean): void;
    static getCustoms(): number;
    static setDevil(v: number): void;
    static getJewel(): number;
    static getAutomatic(): boolean;
    static setIsFirst(): void;
    static getDrugCount(): number;
    static setPos(v: number): void;
}
