export default class SdkManager {
    BannerAd(): void;
    shareInviteQuery(): string;
    CleanData(): void;
    onShow(): void;
    isHaveAddToDesktop(): boolean;
    addColorSign(..._args: any[]): void;
    logEvent(..._args: any[]): void;
    reconnect(): Promise<boolean>;
    showShare(): void;
    InterstitialShow(): void;
    RewardedShow(): Promise<boolean>;
    controlKey(): void;
    SendEvent(..._args: any[]): void;
    InterstitialAd(): void;
    toOtherGame(appId?: string, eventKey?: string, cb?: () => void): void;
    BannerHide(): void;
    postReset(): void;
    BannerShow(): void;
    isHaveShare(): boolean;
    login2(): Promise<boolean>;
    ChannelCallBack(): string;
    goOtherGame(): void;
    login(cb?: () => void, failed?: () => void): void;
    recorderstop(): void;
    FuckWxPlatform(type: string, success?: (() => void) | null, fail?: (() => void) | null, num?: number): void;
    recorderstart(): void;
    shareRecorder(success?: () => void, fail?: () => void): void;
    share(cb?: () => void): void;
    loadData(): void;
    login1(): Promise<boolean>;
    onShareListen(): void;
    BannerShow1(): void;
    RewardedAd(): void;
    copyToClipboard(text: any): Promise<void>;
    isShowAddColorSign(t: Function): void;
    addToFavorites(t: Function, e: Function): void;
    async_login(): Promise<boolean>;
    exit(): void;
    getMenuButtonBottom(): number;
    onHideListen(): void;
}
