import SdkManager from "SdkManager";
export default class WxManager extends SdkManager {
    recordTime: any;
    rewardNum: number;
    interstitialAd: any;
    recorder: any;
    appbox: any;
    bannerAd: any;
    index: number;
    bannerCount: number;
    bannerNum: number;
    recorderTime: number;
    recordvidoe: any;
    bannerRepeat: number;
    _noShareGroup: boolean;
    count: number;
    BannerShow(): void;
    isHaveShare(): boolean;
    ClickShare(success: () => void, fail: () => void): void;
    share(): void;
    customer(): void;
    postReset(): void;
    static cocosToWXPixel(node: any): any;
    login1(): Promise<boolean>;
    AppBoxAd(): void;
    setTranscends(): void;
    hideTranscends(): void;
    MoreGame(): void;
    vibrate(): void;
    showLoading(): void;
    showShare(): void;
    InterstitialShow(): void;
    recorderAd(): void;
    controlKey(): void;
    getWxLoginCode(): Promise<unknown>;
    BannerAd(): void;
    RewardedAd(): Promise<any>;
    onShareListen(): void;
    goOtherGame(): void;
    InterstitialAd(): void;
    setUserData(): void;
    AppBoxShow(): void;
    toOtherGame(appId: string, eventKey: string, cb?: () => void): void;
    onShow(): void;
    onHideListen(): void;
    saveApp(success: () => void, fail: () => void): void;
    getMenuButtonBottom(): number;
    BannerHide(): void;
    recorderstop(): void;
    hideLoading(): void;
    login(cb: () => void): void;
    shareRecorder(success: () => void, fail: () => void): void;
    RewardedShow(): Promise<boolean>;
    hideWXOpen(): void;
    recorderstart(): void;
}
